apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index
      volumes:
        - name: index
          configMap:
            name: nginx-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-r
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index
      volumes:
        - name: index
          configMap:
            name: nginx-2
